@hostname = localhost
@port = 5001
@host = http://{{hostname}}:{{port}}
@contentType = application/json

# Điền ID User sau khi vào đây:
@userId =698337b70478bd00dcc9b4a8

# Điền Access Token sau khi đăng nhập vào đây:
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OTgzMzdiNzA0NzhiZDAwZGNjOWI0YTgiLCJlbWFpbCI6ImV4YW1wbGVAZ21haWwuY29tIiwicm9sZXMiOlsidXNlciJdLCJpYXQiOjE3NzI2MDY5NzYsImV4cCI6MTc3MjYwNzAzNn0.XNb4iB9cOI_H94Q3-ag2JSmY5XEy3OKB5IQQ5rTcook


### ==========================================
### 1. ĐĂNG KÝ
### ==========================================
POST {{host}}/api/user/signup
Content-Type: {{contentType}}

{
  "name": "Lưu Hồng Phúc",
  "email": "luuphuc1368@gmail.com",
  "password": "marigold123"
}

### ==========================================
### 2. ĐĂNG NHẬP
### ==========================================

POST {{host}}/api/user/login
Content-Type: {{contentType}}

{
  "email": "luuphuc1368@gmail.com",
  "password": "marigold123"

}


### ==========================================
### 3. LẤY THÔNG TIN USER
### ==========================================
GET {{host}}/api/user/info/{{userId}}
Authorization: Bearer {{token}}
Content-Type: {{contentType}}
x-client-id: {{userId}}


### ==========================================
### 4. CẬP NHẬT THÔNG TIN
### ==========================================
PUT {{host}}/api/user/update/{{userId}}
Authorization: Bearer {{token}}
x-client-id: {{userId}}
Content-Type: {{contentType}}

{
  "name": "example01"
}


### ==========================================
### 5. THÊM ĐỊA CHỈ
### ==========================================
POST {{host}}/api/user/address/{{userId}}
Authorization: Bearer {{token}}
x-client-id: {{userId}}
Content-Type: {{contentType}}

{
  "street": "123 Bến Thành",
  "city": "Ho Chi Minh",
  "country": "Vietnam",
  "ward": "Phường 1",
  "details": "Gần chợ Bến Thành"
}

### ==========================================
### 6. THÊM ĐỊA CHỈ THỨ 2
### ==========================================
POST {{host}}/api/user/address/{{userId}}
Authorization: Bearer {{token}}
x-client-id: {{userId}}
Content-Type: {{contentType}}

{
  "street": "123 Sối Tiên",
  "city": "Ho Chi Minh",
  "country": "Vietnam",
  "ward": "Phường 6",
  "details": "Gần Bến Xe Miền Đông"
}


### ==========================================
### 7. XÓA ĐỊA CHỈ
### ==========================================
#Số 1 ở cuối URL là index của địa chỉ trong mảng (0 là địa chỉ đầu tiên)
DELETE {{host}}/api/user/address/{{userId}}/1
Authorization: Bearer {{token}}
x-client-id: {{userId}}
Content-Type: {{contentType}}


### ==========================================
### 8. ĐĂNG XUẤT
### ==========================================
# Cần header x-client-id để server biết xóa key của user nào
POST {{host}}/api/user/logout
Authorization: Bearer {{token}}
x-client-id: {{userId}}
Content-Type: {{contentType}}

